[build]
  base = "frontend"
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_CANTON_LEDGER_API = "https://canton-api.cleaportx.com"
  REACT_APP_CANTON_ADMIN_API = "https://canton-admin.cleaportx.com"
  REACT_APP_PARTICIPANT_ID = "cleaportx_participant"
  REACT_APP_NETWORK_NAME = "MainNet"

# SPA fallback for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"